### ISSUE TITLE
JAVA_HOME is not defined

### ISSUE THREAD

**Issue by captainju** [peopledoc/ansible-role-java#1]
Since it is not automatically defined, the CA certificates can not be added to the java keystore.
We can manually define it with `java_home` but it would be better if it was automatic like it is in `novafloss.oracle-java`

**Comment by MaxVigne** [comment]
I modified the role in 7b66b0b52705d01c07778983fd1524e5ef1c4a5c to define the `java_home` var for debian systems with the right default value (which should define `JAVA_HOME` like in `novafloss.oracle-java`).

**Comment by captainju** [comment]
Thanks it works!
